-- AlterTable
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "totpSecretEnc" TEXT;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "totpPendingEnc" TEXT;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "totpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "totpConfirmedAt" TIMESTAMP(3);
