-- AlterTable
ALTER TABLE "NotificationPref" ADD COLUMN IF NOT EXISTS "emailMarketing" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NotificationPref" ADD COLUMN IF NOT EXISTS "pushDeposits" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPref" ADD COLUMN IF NOT EXISTS "pushWithdrawals" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPref" ADD COLUMN IF NOT EXISTS "pushInvestments" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPref" ADD COLUMN IF NOT EXISTS "pushSecurity" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "NotificationPref" ADD COLUMN IF NOT EXISTS "pushKyc" BOOLEAN NOT NULL DEFAULT true;
